#!/usr/bin/env bash
# Install nginx and print out the string "Hello World!"

# Update the package list
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Configure Nginx to listen on port 80
sudo sh -c 'echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        return 200 \"Hello World!\";
    }
}" > /etc/nginx/sites-available/default'

# Reload Nginx to apply the changes
sudo nginx -s reload
