#!/usr/bin/env bash
# Change localhost to 127.0.0.2
# Change facebook.com to 8.8.8.8

# Update the hosts file to configure domain resolutions
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts

# Ensure changes are effective within the Docker environment
docker exec -i $(docker ps -q) sh -c "echo '127.0.0.2 localhost' >> /etc/hosts"
docker exec -i $(docker ps -q) sh -c "echo '8.8.8.8 facebook.com' >> /etc/hosts"

echo "Configuration completed!"
